services:
  chatbot-unb-api:
    image: nathaliaop/chatbot-unb-api:3.0
    container_name: chatbot-unb-api
    restart: unless-stopped
    ports:
      - "7010:4000"
    environment:
      CHAT_TEMPLATE: "Você é um chatbot da Universidade de Brasília feito para responder perguntas sobre assuntos relacionados a universidade. Responda a mensagem do usuário em português utilizando o contexto como base. \n\nContexto: {context}.\n\nUsuário: {user_message}"
      DEEPSEEK_API_KEY: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxx"
      HUGGING_FACE_API_KEY: "hf_xxxxxxxxxxxxxxxxxxxxxxxxxx"
      QDRANT_CLIENT_URL: "https://xxxxxxxxxxx.us-east4-0.gcp.cloud.qdrant.io"
      QDRANT_API_KEY: "your-api-key"
      QDRANT_COLLECTION_NAME: "chatbot-unb"
      QDRANT_SEARCH_LIMIT: "5"